<nav>
        <a href="http://localhost/SiteLuttesEnchantees/Luttes-Enchantees/liste">Liste des membres</a>
        <a href="http://localhost/SiteLuttesEnchantees/Luttes-Enchantees/chants">Chants</a>
        <a href="http://localhost/SiteLuttesEnchantees/Luttes-Enchantees/repes">Agenda</a>
        <a href="http://localhost/SiteLuttesEnchantees/Luttes-Enchantees/messages">Messages</a>
        <a href="http://localhost/SiteLuttesEnchantees/Luttes-Enchantees/echanges">Echanges</a>
        <a href="http://localhost/SiteLuttesEnchantees/Luttes-Enchantees/videos">Vidéos</a>
    </nav>