<nav id="membersNav">

	<a href="http://localhost/Luttes-Enchantees/liste">Liste des membres</a>
	<a href="http://localhost/Luttes-Enchantees/chants">Chants</a>
	<a href="http://localhost/Luttes-Enchantees/repes">Agenda</a>
	<a href="http://localhost/Luttes-Enchantees/messages">Messages</a>
	<a href="http://localhost/Luttes-Enchantees/echanges">Echanges</a>
	<a href="http://localhost/Luttes-Enchantees/videos">Vidéos</a>
</nav>