<main id="adminSongs">

	<?php
	require "./templates/_adminNav.phtml"
	?>

	<h1>Gestion des chants</h1>

	<?php
	require "./templates/_messages.phtml"
	?>

	<p>Permet d'ajouter un nouveau chant ou de télécharger des fichiers en lien avec un chant existant</p>

	<section>

		<h2>Ajouter un nouveau chant</h2>

		<form id="newSong"
		      action="/Luttes-Enchantees/admin-chants"
		      method="post">

			<input type="hidden" id="newSongAction" name="action" value="addSong">

			<label for="newSongTitle">Titre :</label>
			<input type="text" id="newSongTitle" name="title">

			<label for="newSongDescription">Description :</label>
			<input type="text" id="newSongDescription" name="description">

			<input class="button" type="submit" value="Créer">
		</form>

	</section>

	<section>
		<h2>Choisir un chant existant</h2>

		<ul>
			<?php
			foreach($data["allSongs"] as $key => $song)
			{
			?>
				<li>
					<article>

						<h3><?=$song["title"]; ?></h3>

						<form id="addVoice"
							action="/Luttes-Enchantees/admin-voix"
							method="post">

							<input type="hidden" id="newVoiceAction" name="action" value="addVoice">
							<input type="hidden" id="newVoiceId" name="songId" value="<?= $song["id"]; ?>">

							<input class="button" type="submit" value="Ajouter une voix">
						</form>

						<form id="addText"
							action="/Luttes-Enchantees/admin-texte"
							method="post">

							<input type="hidden" id="newTextAction" name="action" value="addText">
							<input type="hidden" id="newTextId" name="songId" value="<?= $song["id"]; ?>">

							<input class="button" type="submit" value="Ajouter un texte">
						</form>

						<form id="addVideo"
							action="/Luttes-Enchantees/admin-video"
							method="post">

							<input type="hidden" id="newVideoAction" name="action" value="addVideo">
							<input type="hidden" id="newVideoId" name="songId" value="<?= $song["id"]; ?>">

							<input class="button" type="submit" value="Ajouter une video">
						</form>

						<form id="addCurrent"
							action="/Luttes-Enchantees/admin-moment"
							method="post">

							<input type="hidden" id="newCurrentAction" name="action" value="addCurrent">
							<input type="hidden" id="newCurrentId" name="songId" value="<?= $song["id"]; ?>">

							<input class="button" type="submit" value="Changer le statut">
						</form>

					</article>

				</li>
			<?php
			}
			?>
		</ul>

	</section>

</main>