<main id="adminUpdateEvents">
	<?php
	$event = $data["event"];
	$id = $event->getId();
      $date = $event->getDate();
      $tempDate = explode("-", $date);
      $dateForInput = $tempDate[2] . "-" . $tempDate[1] . "-" . $tempDate[0];
      $eventCatId = $event->getEventCatId();
      $privateDetails = $event->getPrivateDetails();
      $publicDetails = $event->getPublicDetails();
      $status = $event->getStatus();
      $cat = $data["cat"];
	?>

	<figure>
		<img class="logo" src="../assets/img/logo1.png" alt="Logo des Luttes Enchantées">
	</figure>

	<h1><?= $cat; ?> du <?= $date; ?></h1>

	<?php
	require "./templates/_messages.phtml";
	?>

	<form  id="updateEventForm"
		 action="/Luttes-Enchantees/admin-modif-date/<?= $id; ?>"
		 method="post">

		<input type="hidden"
			id="updateEvent"
			name="action"
			value="updateEvent">
		<input type="hidden"
			name="route"
			value="param">
		<input type="hidden"
				id="eventId"
				name="eventId"
				value="<?= $id; ?>">

		<fieldset>
			<legend>Choisir une catégorie :</legend>

			<?php
			foreach($data["cats"] as $key => $catItem)
			{
			?>
				<input type="radio" name="cat" value="<?= $catItem["id"]; ?>"
				<?php
				if(intval($catItem["id"]) === $eventCatId)
				{
				?>
					checked
				<?php
				}
				?>
				>
				<label for="cat"><?= $catItem["name"]; ?></label>
			<?php
			}
			?>
		</fieldset>

		<fieldset>
			<legend>Cet événement est il interne ou public ?</legend>

				<input type="radio" name="status" value=1
				<?php
					if(isset($status) && $status)
					{
					?>
						checked
					<?php
					}
				?>
				>
				<label for="cat">Interne</label>
				
				<input type="radio" name="status" value=0
				<?php
					if(isset($status) && !$status)
					{
					?>
						checked
					<?php
					}
				?>
				>
				<label for="cat">Public</label>
		</fieldset>

		<fieldset id="dateFieldset">
			<label id="dateLabel" for="date">Date : </label>
			<input type="date"
					id="dateInput"
					name="date"
					value="<?= $dateForInput; ?>">
		</fieldset>

		<fieldset id="privateDetailsFieldset">
			<label for="privateDetails">Infos membres : </label>
			<textarea
				name="privateDetails"
				id="privateDetails"
				rows="5" cols="80"
				maxlength="1024"><?php
				if(isset($data["event"]))
				{
				echo $privateDetails;
				}
				?></textarea>
		</fieldset>

		<fieldset id="publicDetailsFieldset">
			<label for="publicDetails">Infos publiques : </label>
			<textarea
				name="publicDetails"
				id="publicDetails"
				rows="5" cols="80"
				maxlength="1024"><?php
				if(isset($data["event"]))
				{
				echo $publicDetails;
				}
				?></textarea>
		</fieldset>

		<input class="button"
			 type="submit"
			 value="Modifier">
	</form>


</main>