<main id="adminAddVoice">

	<h1>Gestion des fichiers sons</h3>

	<?php
	require "./templates/_messages.phtml";
	?>

	<h2>Télécharger des fichiers son pour <?= $data["title"]; ?></h2>

	<form  id="uploader"
		action="/Luttes-Enchantees/admin-voix"
		method="post"
		enctype="multipart/form-data">

		<input type="hidden" id="uploadVoice" name="action" value="uploadVoice">
		<input type="hidden" id="songId" name="songId" value= "<?= $_POST["songId"]; ?> ">
	
		<fieldset>
			<legend>Choisir un fichier à télécharger:</legend>

			<input type="radio" id="aigue" name="voice" value="aigue">
			<label for="aigue">Aigüe</label>

			<input type="radio" id="medium" name="voice" value="medium">
			<label for="medium">Medium</label>

			<input type="radio" id="grave" name="voice" value="grave">
			<label for="grave">Grave</label>

			<input type="radio" id="mix" name="voice" value="mix">
			<label for="mix">Mix</label>

			<input type="radio" id="demo" name="voice" value="demo">
			<label for="demo">Démo</label>

			<input type="radio" id="other" name="voice" value="other">
			<label for="other">Autre</label>
			<label for="otherVoice"> : </label>
			<input type="text" id="otherVoice" name="other" />
		</fieldset>


		<input type="file"
			name="fileToUpload"
			id="fileToUpload">
			
		<input class="button"
			 type="submit">

	</form>

</main>