<main id="adminAddVideo">

	<figure>
		<img class="logo" src="./assets/img/logo1.png" alt="Logo des Luttes Enchantées">
	</figure>

	<h1>Gestion des liens vidéos</h3>

	<?php
	require "./templates/_messages.phtml";
	?>

	<h2>insérer un lien vidéo pour <?= $data["title"]; ?></h2>

	<form class="addVideo"
		action="/Luttes-Enchantees/admin-video"
		method="post">

	<input type="hidden" id="uploadVideo" name="action" value="addVideoLink">
	<input type="hidden" id="songId" name="songId" value= "<?= $_POST["songId"]; ?> ">
		
	<label for="urlVideo">Copier le lien içi :</label>
      <input type="text" id="urlVideo" name ="urlVideo">
			
	<input class="button"
		 type="submit">

	</form>

	<article class="changeSongItemArt">

		<h3>Modifier un autre élément de <?= $data["title"]; ?></h3>

		<form id="addVoice"
			action="/Luttes-Enchantees/admin-voix"
			method="post">

			<input type="hidden" id="newVoiceAction" name="action" value="addVoice">
			<input type="hidden" id="newVoiceId" name="songId" value="<?= $_POST["songId"]; ?>">

			<input class="button" type="submit" value="Ajouter une voix">
		</form>

		<form id="addText"
			action="/Luttes-Enchantees/admin-texte"
			method="post">

			<input type="hidden" id="newTextAction" name="action" value="addText">
			<input type="hidden" id="newTextId" name="songId" value="<?= $_POST["songId"]; ?>">

			<input class="button" type="submit" value="Ajouter un texte">
		</form>

		<form id="modify"
			action="/Luttes-Enchantees/admin-modif"
			method="post">

			<input type="hidden" id="newCurrentAction" name="action" value="modify">
			<input type="hidden" id="newCurrentId" name="songId" value="<?= $_POST["songId"]; ?>">

			<input class="button" type="submit" value="Modifier">
		</form>

	</article>


      <section>

            <h2>Marche à suivre</h2>
            <p>Pour intégrer facilement un lien youtube sur une page web, aller sur la page youtube de la vidéo.</p>
            
		<p>Sous la vidéo à droite cliquer sur "Partager"</p>
		<figure>
      	      <img src="./assets/img/addVideoLink1.jpg">
		</figure>

            <p>Dans la Dans la fenetre qui s'est ouverte, cliquer sur "Intégrer"</p>
		<figure>
	            <img src="./assets/img/addVideoLink2.jpg">
		</figure>

		<p>Dans la nouvelle fenêtre, cliquer sur "Copier" en bas à droite</p>
		<figure>
      	      <img src="./assets/img/addVideoLink3.jpg">
		</figure>

		<p>Il n'y a plus qu'a revenir sur ce site et faire coller dans le champ "Copier le lien içi"</p>
      </section>

</main>