<main id="adminAddText">


	<h1>Gestion des fichiers paroles</h3>

	<?php
	require "./templates/_messages.phtml";
	var_dump($_POST);
	var_dump($data);
	?>

	<h2>Télécharger un fichier paroles pour <?= $data["title"]; ?></h2>

	<form  id="uploader"
		action="/Luttes-Enchantees/admin-texte"
		method="post"
		enctype="multipart/form-data">

	<input type="hidden" id="uploadVoice" name="action" value="uploadText">
	<input type="hidden" id="songId" name="songId" value= "<?= $_POST["songId"]; ?> ">
		
	<input type="file"
		 name="fileToUpload"
		 id="fileToUpload">
			
		<input class="button"
			 type="submit">

	</form>

	<article class="changeSongItemArt">

		<form id="addVoice"
			action="/Luttes-Enchantees/admin-voix"
			method="post">

			<input type="hidden" id="newVoiceAction" name="action" value="addVoice">
			<input type="hidden" id="newVoiceId" name="songId" value="<?= $_POST["songId"]; ?>">

			<input class="button" type="submit" value="Ajouter une voix">
		</form>

		<form id="addVideo"
			action="/Luttes-Enchantees/admin-video"
			method="post">

			<input type="hidden" id="newVideoAction" name="action" value="addVideo">
			<input type="hidden" id="newVideoId" name="songId" value="<?= $_POST["songId"]; ?>">

			<input class="button" type="submit" value="Ajouter une video">
		</form>

		<form id="addCurrent"
			action="/Luttes-Enchantees/admin-modif"
			method="post">

			<input type="hidden" id="newCurrentAction" name="action" value="modify">
			<input type="hidden" id="newCurrentId" name="songId" value="<?= $_POST["songId"]; ?>">

			<input class="button" type="submit" value="Modifier">
		</form>

	</article>


</main>