<main id="adminCurrent">

	<h1>Gestion du statut "chant du moment"</h3>

	<?php
	require "./templates/_messages.phtml";
	var_dump($_POST);
	?>

	<h2>Changer le statut pour <?= $data["title"]; ?></h2>

	<fieldset>
		<legend>Mettre <?= $data["title"]; ?> en "chant du moment" ?</legend>

		<form  id="changeStatus"
			action="/Luttes-Enchantees/admin-moment"
			method="post">

			<input type="hidden" id="updateStatus" name="action" value="updateStatus">
			<input type="hidden" id="songId" name="songId" value= "<?= $_POST["songId"]; ?> ">
				
			<input type="radio" id="urlVideo1" name ="status" value=1>
			<label for="urlVideo1">Oui</label>
			<input type="radio" id="urlVideo0" name ="status" value=0>
			<label for="urlVideo0">Non</label>

			<input class="button"
				type="submit">

		</form>
	</fieldset>

	<article class="changeSongItemArt">

		<form id="addVoice"
			action="/Luttes-Enchantees/admin-voix"
			method="post">

			<input type="hidden" id="newVoiceAction" name="action" value="addVoice">
			<input type="hidden" id="newVoiceId" name="songId" value="<?= $_POST["songId"]; ?>">

			<input class="button" type="submit" value="Ajouter une voix">
		</form>

		<form id="addText"
			action="/Luttes-Enchantees/admin-texte"
			method="post">

			<input type="hidden" id="newTextAction" name="action" value="addText">
			<input type="hidden" id="newTextId" name="songId" value="<?= $_POST["songId"]; ?>">

			<input class="button" type="submit" value="Ajouter un texte">
		</form>

		<form id="addVideo"
			action="/Luttes-Enchantees/admin-video"
			method="post">

			<input type="hidden" id="newVideoAction" name="action" value="addVideo">
			<input type="hidden" id="newVideoId" name="songId" value="<?= $_POST["songId"]; ?>">

			<input class="button" type="submit" value="Ajouter une video">
		</form>

	</article>

</main>