<main id="contact">

	<figure>
		<img class="logo" src="./assets/img/logo1.png" alt="Logo des Luttes Enchantées">
	</figure>
	
	<h1>Nous contacter</h1>

	<p>Nous sommes au complet pour l'instant, nous n'acceptons donc pas de nouvelles choristes.</p>
	<p>Vous pouvez nous contacter si vous voulez nous proposer de chanter lors d'un évenement que vous organisez.</p>
	<p>Pour cela merci de remplir le formulaire ci dessous, nous vous répondrons dans les meilleurs délais.</p>

	<form id="contactForm"
			action="/Luttes-Enchantees/envoi-mail"
			method="post">

		<input type="hidden"
			 id="newMail"
			 name="action"
			 value="newMail">

		<label id="mailAdressLabel" for="mailObject">Votre adresse mail : </label>
		<input type="mail" name="mailAdress" id="mailAdress">
			
		<label id="mailObjectLabel" for="mailObject">Objet : </label>
		<textarea
			name="mailObject"
			id="mailObject"
			maxlength="155"></textarea>

		<label id="mailContentLabel" for="mailContent">Contenu : </label>
		<textarea
			name="mailContent"
			id="mailContent"
			maxlength="1024"></textarea>
				
		<input id="contactFormSubmit"
			 class="button"
			 type="submit"
			 value="Envoyer">
	</form>
</main>
