<main id="home">

	<h1>Bienvenue sur le site des Luttes Enchantées</h1>

	<p id="homeFirstP">Luttes enchantées, c'est une chorale de femmes, féministes</p>

	<section id="homePresentation">
		
			<h2>Qui sommes nous ?</h2>

			<figure>
				<img src="./assets/img/230922.jpg"
				alt="Photo de la chorale en concert - septembre 2022">
				<figcaption>Photo de concert - septembre 2022</figcaption>
			</figure>

			<section>
				<p>Les Luttes Enchantées existent depuis le 15 décembre 2018.</p>

				<p>Nous sommes une chorale rennaise, composée d’une trentaine de femmes de tous âges, qui aimons nous retrouver autour d’un répertoire féministe.</p>

				<p>Le but est de se faire plaisir tout en travaillant nos voix et en apprenant des chants dynamiques pouvant être chantés en manifs ou en concert, avec ou sans cheffe de chœur.</p>

				<p>Notre chorale est aussi un lieu de partages et d’informations, nous aimons nous retrouver autour des luttes des femmes avec un répertoire commun à plusieurs chorales féministes sur la ville, comme <a href="https://www.lako-compagnie.com/colectiva" target="_blank" title="lien vers le
				site de la Ko-compagnie">!Colectiva!</a> ou la <a href="https://latetealest.wixsite.com/latetealest" target="_blank" title="lien vers le
				site de la Tête à l'Est"> Tête à l'Est</a></p>

				<p>Nous aimons chanter en manifs, et lors d’évènements auxquels nous invitent des associations, groupes, chorales alliées. En 2022, par exemple, nous avons chanté au festival de <a href="https://www.facebook.com/NousToutes35/" target="_blank" title="lien vers le site de Nous Toutes 35">Nous Toutes 35</a>, pour les 10 ans de l'association <a href="http://histoire-feminisme-rennes.blogspot.com/" target="_blank" title="lien vers le site d'HFR">Histoire du Féminisme à Rennes</a>, pendant l'académie d'été du DIU "Etudes sur le genre" à Rennes 2, et dans différentes manifs comme le 25 novembre lors de la <a href="https://www.facebook.com/events/389434949944187/?ref=newsfeed" target="blank" title="lien vers l'évenement de Nous Toutes 35">marche contre les violences faites aux femmes</a> avec !Colectiva!, et lors de bien d'autres évenements !</p>

			</section>

	</section>
	
	<section id="homeActu">
		<h2>Nos actualités :</h2>

		<ul>
			<?php
			foreach ($data["events"] as $key => $event)
			{
			?>
				<li>
					<h3 class="homeActuH3"><?= $event["cat"]; ?> du <?= $event["date"]; ?> :</h3>
					<p><?= $event["public_details"]; ?></p>
				</li>
			<?php
			}
			?>
		</ul>
	</section>

	<section id="homeChants">
		<h2>Nos chants</h2>

		<p>Notre répértoire est composé de chants féministes et de chants de femmes.</p>
		<p>Voici quelques exemples de chants que nous travaillons actuellement</p>

		<?php
            foreach ($data["songs"] as $key => $song)
		{
            ?>
			<article class="homeChantsArticle">
				<h3><?= $song["title"]; ?></h3>
				
				<?php
				if(isset($song["description"]) && $song["description"] !== "")
				{
				?>
					<p><?= $song["description"]; ?></p>
				<?php
				}
				?>
				
				<?php
				if(isset($song["urlVideo"]) && $song["urlVideo"] !== "")
				{
				?>
					<figure class="homeUrlVideo"><?= $song["urlVideo"]; ?></figure>
				<?php
				}
				?>
			</article>
		<?php
            }
		?>

</main>
	