<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<meta name="description" content="Luttes Enchantées, chorale de femmes, féministe, sur Rennes">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Luttes Enchantées</title>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jgthms/minireset.css@master/minireset.min.css">
		<link rel="stylesheet" href="./assets/css/style.css" type="text/css">
	</head>
	
	<body id="top">
		
		<?php
			require "./templates/_header.phtml";

			if($_SESSION !== [])
			{
				if(isset($_SESSION["connectUser"]) && $_SESSION["connectUser"])
				{
					require "./templates/_membersNav.phtml";

					if($_SESSION["user"]["role"] === "admin")
					{
						require "./templates/_adminNav.phtml";
					}
				}
			}

			require "./templates/$template.phtml";
			require "./templates/_footer.phtml";
		?>
	   
	</body>
	
</html>