<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<meta name="description" content="Luttes Enchantées, chorale de femmes, féministe, sur Rennes. On se retrouve pour chanter autour des luttes des femmes, du 8 mars et du 25 novembre, entre autres...">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Luttes Enchantées</title>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jgthms/minireset.css@master/minireset.min.css">
		<?php
		if(isset($_POST["route"]) && $_POST["route"] === "param")
		{
		?>
	            <link rel="icon" type="image/png" href="../assets/img/logo1.png">
			<link rel="stylesheet" href="../assets/css/style.css" type="text/css">
		<?php
		}
		else
		{
		?>
	            <link rel="icon" type="image/png" href="./assets/img/logo1.png">
			<link rel="stylesheet" href="./assets/css/style.css" type="text/css">
		<?php
		}
		?>
		<link href="https://fonts.googleapis.com/css2?family=Handlee&family=Neucha&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css2?family=Kalam:wght@300;400;700&display=swap" rel="stylesheet"> 
	</head>
	
	<body id="top">
		<header>
		<?php
			require "./templates/_header.phtml";

			if($_SESSION !== [])
			{
				if(isset($_SESSION["connectUser"]) && $_SESSION["connectUser"])
				{
					require "./templates/_membersNav.phtml";

					if($_SESSION["user"]["role"] === "admin")
					{
						require "./templates/_adminNav.phtml";
					}
				}
			}
		?>
		</header>
		<?php
			require "./templates/$template.phtml";
			require "./templates/_footer.phtml";
		?>
	   
	</body>
	
</html>