<main id="membersVideos">

	<figure>
		<img class="logo" src="./assets/img/2.png" alt="Logo des Luttes Enchantées">
	</figure>

	<h1>Vidéos - Photos</h1>

	<p>Les images des nos prestations, quand on en a</p>

	<h2>Concert du 11/06/2022 à Chorales Aux Champs</h2>

	<article class="membersVideosArt">
		<h3>Le jeu de la Marelle</h3>

		<video controls width="500">
			<source src="./assets/videos/VID_20220611_192233.mp4"
				type="video/mp4">

			Le jeu de la Marelle
			<a href="./assets/videos/VID_20220611_192233.mp4"></a>
		</video>
	</article>

	<article class="membersVideosArt">
		<h3>Je suis fille de</h3>

		<video controls width="500">
			<source src="./assets/videos/VID_20220611_192946.mp4"
				type="video/mp4">

			Je suis fille de
			<a href="./assets/videos/VID_20220611_192946.mp4"></a>
		</video>
	</article>

	<article class="membersVideosArt">
		<h3>My eyes</h3>

		<video controls width="500">
			<source src="./assets/videos/VID_20220611_193359.mp4"
				type="video/mp4">

			My eyes
			<a href="./assets/videos/VID_20220611_193359.mp4"></a>
		</video>
	</article>

	<article class="membersVideosArt">
		<h3>Le Otto Ore</h3>

		<video controls width="500">
			<source src="./assets/videos/VID_20220611_194836.mp4"
				type="video/mp4">

				Le Otto Ore
			<a href="./assets/videos/VID_20220611_194836.mp4"></a>
		</video>
	</article>

	<article class="membersVideosArt">
		<h3>Duas Cirandas</h3>

		<video controls width="500">
			<source src="./assets/videos/VID_20220611_195113.mp4"
				type="video/mp4">

			Duas Cirandas
			<a href="./assets/videos/VID_20220611_195113.mp4"></a>
		</video>
	</article>
</main>