<main id="membersAccounts">

    <figure>
		<img class="logo" src="./assets/img/logo1.png" alt="Logo des Luttes Enchantées">
	</figure>

	<section id="membersAccountsSect">

		<h1>Comptes</h1>

		<p id="membersAccountsFirstP">Comptes au 14/01/23</p>

		<table>
			<thead>
				<tr>
					<th>Opérations</th>
					<th>Recettes</th>
					<th>Dépenses</th>
					<th>Solde</th>
				</tr>
			</thead>
			<tbody>
			<tr>
					<td>Solde 2022</td>
					<td class="alignR">600</td>
					<td class="alignR"></td>
					<td class="alignR">600</td>
				</tr>
				<tr>
					<td>Séance du 23/09</td>
					<td class="alignR"></td>
					<td class="alignR">240</td>
					<td class="alignR">360</td>
				</tr>
				<tr>
					<td>Cotisations 5/10</td>
					<td class="alignR">1 400</td>
					<td class="alignR"></td>
					<td class="alignR">1 760</td>
				</tr>
				<tr>
					<td>Séance Charlotte 5/10</td>
					<td class="alignR"></td>
					<td class="alignR">180</td>
					<td class="alignR">1 580</td>
				</tr>
				<tr>
					<td>Photocopies</td>
					<td class="alignR"></td>
					<td class="alignR">74</td>
					<td class="alignR">1 506</td>
				</tr>
				<tr>
					<td>Séance Charlotte 19/11</td>
					<td class="alignR"></td>
					<td class="alignR">180</td>
					<td class="alignR">1 326</td>
				</tr>
				<tr>
					<td>Photocopies 19/11</td>
					<td class="alignR">10</td>
					<td class="alignR"></td>
					<td class="alignR">1 316</td>
				</tr>
				<tr>
					<td>Cotisations 19/11</td>
					<td class="alignR">680</td>
					<td class="alignR"></td>
					<td class="alignR">1 996</td>
				</tr>
				<tr>
					<td>Cotisations 10/12</td>
					<td class="alignR">230</td>
					<td class="alignR"></td>
					<td class="alignR">2 226</td>
				</tr>
				<tr>
					<td>Séance Charlotte 10/12</td>
					<td class="alignR"></td>
					<td class="alignR">300</td>
					<td class="alignR">1 926</td>
				</tr>
				<tr>
					<td>Cotisations 14/01</td>
					<td class="alignR">80</td>
					<td class="alignR"></td>
					<td class="alignR">2 006</td>
				</tr>
				<tr>
					<td>Séance Charlotte 14/01</td>
					<td class="alignR"></td>
					<td class="alignR">180</td>
					<td class="alignR">1 826</td>
				</tr>
				<tr>
					<td>Indemnisation créatrice site</td>
					<td class="alignR"></td>
					<td class="alignR">500</td>
					<td class="alignR">1 326</td>
				</tr>
			</tbody>
			<tfoot>
				<tr>
					<td class="total tableFooter">Total</td>
					<td class="alignR tableFooter">2 990</td>
					<td class="alignR tableFooter">1 664</td>
					<td class="alignR tableFooter"></td>				</tr>
			</tfoot>
		</table>
	</section>

	<section id="membersAccountsCom">
		<h2>Commentaires :</h2>
		<p>Base cotisation 80 euros</p>

		<h2>Dépenses à venir :</h2>

		<p>5 séances de 3h = 900 euros</p>
		<p>Hébergement site 7 euros * 8 mois = 56 euros</p>

	</section>

</main>