<main id="membersChat">

	<h1>Messages</h1>

	<?php
	require "./templates/_messages.phtml";
	?>

	<p>Les messages envoyés ici seront visibles par l'ensemble des adhérentes.</p>

	<section id="sendNewChatItem">

		<h2>Envoyer un message</h2>

		<form id="newChatForm"
			action="/Luttes-Enchantees/messages"
			method="post">

			<input type="hidden" id="newChat" name="action" value="newChat">

			<fieldset class="newChatTitleField">
				<label for="newChatTitle">Titre :</label>
				<input type="text" id="newChatTitle" name="title" value="<?php
				if(isset($_POST["title"]) && $_POST["title"] !== "")
				{
					echo $_POST["title"];
				}
				?>">
			</fieldset>

			<fieldset class="newChatContentField">
				<label for="newChatContent">Message : </label>
				<textarea
					name="content"
					id="newChatContent"><?php
					if(isset($_POST["content"]) && $_POST["content"] !== "")
					{
					echo $_POST["content"];
					}
					?></textarea>
			</fieldset>

			<input class="button newChatButton"
				type="submit" value="Envoyer">
		</form>

	</section>

	<section id="displayAllMessages">

		<h2>Liste des messages</h2>
		
		<ul>
			<?php
				foreach($data["allChats"] as $key => $chatItem)
				{
				?>
					<li>
						<h3 class="displayAllMessagesTitle"><?= $chatItem["title"]; ?></h3>
						<p class="displayAllMessagesMessage"><?= $chatItem["message"]; ?></p>
						<p class="displayAllMessagesName"><?= $chatItem["name"]; ?></p>
						<?php
						if(isset($chatItem["answers"]))
						{
							foreach($chatItem["answers"] as $key => $answer)
							{
							?>
								<p class="displayAllMessagesAwser"><?= $answer["content"]; ?></p>
								<p class="displayAllMessagesAwserName"><?= $answer["name"]; ?></p>
							<?php
							}
						}
						?>

						<form id="chatAnswerForm"
							 action="/Luttes-Enchantees/messages"
							 method="post">

							<input type="hidden" id="chatAnswer" name="action" value="chatAnswer">
							<input type="hidden" id="userName" name="userName" value= "<?= $_SESSION["user"]["name"]; ?>">
							<input type="hidden" id="chatId" name="chatId" value= "<?= $chatItem["id"]; ?>">

							<textarea
								name="chatAnswerMessage"
								id="chatAnswerMessage"
								rows="3" cols="80"
								maxlength="1024"></textarea>

							<input class="button"
								 type="submit" value="Répondre">
						</form>
					</li>
				<?php
				}
			?>
		</ul>

	</section>

</main>