<main id="membersEvents">

       <?php
       require "./templates/_membersNav.phtml";
       ?>

       <h1>Agenda</h1>

       <h2>Voici les évenements à venir :</h2>

       <?php
		foreach($data["events"] as $key => $event)
		{
		?>
			<h3><?= $event["date"]; ?></h3>
			<?php
			foreach($data["cats"] as $key => $cat)
			{
				if($cat["id"] === $event["event_cat_id"])
				{
				?>
					<p><?=$cat["name"]; ?>
				<?php
				}
			}

			if($event["status"] === "1")
			{
			?>
				<p>Evenement privé</p>
			<?php
			}
			else
			{
			?>
				<p>Evenement public</p>
			<?php	
			}
			?>
			<p>Présentes : <?= $event["oui"]; ?></p>
			<p>Absentes : <?= $event["non"]; ?></p>
			<p>Ne savent pas : <?= $event["nsp"]; ?></p>
			<p>Non répondu : <?= $event["nonrep"]; ?></p>
			<p><?= $event["private_details"]; ?></p>
			<p><?= $event["public_details"]; ?></p>

			<?php
			$id = intval($event["id"]);
			?>

			<form id="displayUpdateEventForm"
			      action="/Luttes-Enchantees/detail-date/<?= $id; ?>"
			      method="post">

				<input type="hidden"
					id="eventDetail"
					name="action"
					value="eventDetail">
				<input type="hidden"
					 id="eventId"
					 name="eventId"
					 value="<?= $id; ?>">
				<input class="button"
					 type="submit"
					 value="Voir le détail">
			</form>
		
		<?php
		}
		?>
	</section>


</main>