<main id="membersHome">

	<figure>
		<img class="logo" src="./assets/img/LogoLuttesEnchantees.png" alt="Logo des Luttes Enchantées">
	</figure>

	<h1>Bonjour <?= $_SESSION["user"]["name"]; ?>, bienvenue sur l'espace réservé aux membres des Luttes Enchantées</h1>

	<form id="disconnect"
		action="/Luttes-Enchantees/deconnexion"
		method="post">

		<input id="disconnect" class="button" type="submit" value="Me déconnecter">
	</form>

	<section>
		<h2>Prochaines dates</h2>

		<?php
            
		foreach($data["events"] as $key => $event)
		{
		?>
			<section class="membersHomeEvent">
				<h3><?= $event["cat"]; ?> du <?= $event["date"]; ?></h3>
				<p><?= $event["private_details"]; ?></p>

				<?php

				?>

				<form class="setParticipationForm"
					action="/Luttes-Enchantees/accueil-membres"
					method="post">

					<input type="hidden" id="setParticipationAction" name="action" value="setParticipation">
					<input type="hidden" id="participationUserId" name="userId" value="<?= $_SESSION["user"]["id"]; ?>">
					<input type="hidden" id="participationEventId" name="eventId" value="<?= $event["id"]; ?>">

					<fieldset class="setParticipationFieldset">
						<legend class="setPartLegend">Je serais présente à cette date :</legend>

						<span class="setPartRadio">
							<input type="radio" id="oui" name="participation" value="Oui"
							<?php
								if($event["part"] === "Oui")
								{
								?>
									checked
								<?php
								}
							?>
							>
							<label for="oui">Oui</label>

							<input type="radio" id="non" name="participation" value="Non"
							<?php
								if($event["part"] === "Non")
								{
								?>
									checked
								<?php
								}
							?>
							>
							<label for="non">Non</label>

							<input type="radio" id="jnsp" name="participation" value="Je ne sais pas"
							<?php
								if($event["part"] === "Je ne sais pas")
								{
								?>
									checked
								<?php
								}
							?>
							>
							<label for="jnsp">Je ne sais pas</label>

							<input type="radio" id="nonRepondu" name="participation" value="Non répondu"
							<?php
								if($event["part"] === "Non répondu")
								{
								?>
									checked
								<?php
								}
							?>
							>
							<label for="nonRepondu">Non répondu</label>
						</span>

					</fieldset>

					<input class="button" type="submit" value="Valider ma réponse">
				</form>
			</section>
		<?php
		}
		?>
	</section>

</main>