<main id="membersList">

	<h1>Liste des membres</h1>

	<ul>

		<?php
			foreach($data["users"] as $key => $user)
			{
			?>
				<li class="membersListItem">
					<p class="membersListName"><?= $user["name"]; ?></p>
					<?php
					if(intval($user["agreement"]) === 1)
					{
					?>
						<p class="membersListEmail"><?= $user["email"]; ?></p>
					<?php
					} else if(intval($user["agreement"]) === 2)
					{
					?>
						<p class="membersListEmail"><?= $user["email"]; ?></p>
						<p class="membersListTel"><?= $user["tel"]; ?></p>
					<?php
					}
					?>
				</li>
			<?php
			}
		?>
	</ul>
</main>