<main id="membersSharingZone">

	<figure>
		<img class="logo" src="./assets/img/logo1.png" alt="Logo des Luttes Enchantées">
	</figure>

	<h1>Espace d'échange</h1>

	<?php
	require "./templates/_messages.phtml";
	?>

	<p class="membersSharingZoneP">Ici un espace pour s'échanger des recettes, idées de lecture, spectacles, films...</p>

	<section>
		<h2 class="membersSharingZoneH2">Ajouter un échange</h2>

		<p class="membersSharingZoneP">Pour créer un nouvel échange, clique sur la catégorie concernée :</p>

		<ul class="sharingMessageForm">
			<?php
				foreach($data["allCats"] as $key => $cat)
				{
				?>
					<li>
						<form id="newSharingMessageForm"
							action="/Luttes-Enchantees/nouvel-echange"
							method="post">

							<input type="hidden" id="newSharingMessage" name="action" value="newSharingMessage">
							<input type="hidden" id="catId" name="catId" value= "<?= $cat["id"]; ?>">
							<input type="hidden" id="catName" name="catName" value= "<?= $cat["name"]; ?>">

							<input class="button newSharingMessageButton"
								type="submit" value="<?= $cat["name"]; ?>">
						</form>
					</li>
				<?php
				}
			?>
		</ul>
	</section>

	<section>
		
		<h2 class="membersSharingZoneH2">Echanges</h2>

		<p class="membersSharingZoneP">Voici l'ensemble des échanges, si tu veux voir uniquement ceux d'une catégorie, clique sur la catégorie concernée</p>

		<ul class="sharingMessageForm">
			<?php
				foreach($data["allCats"] as $key => $cat)
				{
				?>
					<li>
						<form id="displaySharingMessagesForm"
							action="/Luttes-Enchantees/echanges-par-categorie"
							method="post">

							<input type="hidden" id="displaySharingMessage" name="action" value="displaySharingMessage">
							<input type="hidden" id="catId" name="catId" value= "<?= $cat["id"]; ?>">
							<input type="hidden" id="catName" name="catName" value= "<?= $cat["name"]; ?>">

							<input class="button newSharingMessageButton"
								 type="submit" value="<?= $cat["name"]; ?>">
						</form>
					</li>
				<?php
				}
			?>
		</ul>
	</section>

	<section class="displayAllShares">
		<ul>
			<?php
			foreach($data["allShares"] as $key => $share)
			{
			?>
				<li>
					<h3 class="displayAllSharesCat">Catégorie : <?= $share["catName"]; ?></h3>

					<h2 class="displayAllSharesTitle"><?= $share["title"]; ?></h2>

					<p class="displayAllSharesMessage"><?= $share["content"]; ?></p>

					<p class="displayAllSharesName"><?= $share["name"]; ?></p>

					<?php
						if(isset($share["answers"]) && $share["answers"] !== [])
						{
							foreach($share["answers"] as $key => $answer)
							{
							?>
								<p class="displayAllSharesAwser"><?= $answer["content"]; ?></p>
								<p class="displayAllSharesAwserName"><?= $answer["name"]; ?></p>
							<?php
							}
						}
					?>

					<form  id="displayAllSharesForm"
						action="/Luttes-Enchantees/echanges"
						method="post">

						<input type="hidden" id="shareAnswer" name="action" value="shareAnswer">
						<input type="hidden" id="catId" name="catId" value= "<?= $share["category_id"]; ?>">
						<input type="hidden" id="catName" name="catName" value= "<?= $share["catName"]; ?>">
						<input type="hidden" id="userName" name="userName" value= "<?= $_SESSION["user"]["name"]; ?>">
						<input type="hidden" id="shareId" name="shareId" value= "<?= $share["id"]; ?>">

						<textarea
							name="shareAnswerContent"
							id="shareAnswerContent"
							rows="3" cols="80"
							maxlength="1024"></textarea>

						<input class="button"
							type="submit" value="Répondre">
					</form>
				</li>
			<?php
			}
			?>
		</ul>
	</section>

</main>