<main id="membersAccounts">

    <figure>
		<img class="logo" src="./assets/img/logo1.png" alt="Logo des Luttes Enchantées">
	</figure>

	<h1>Comptes 20022-2023</h1>

    <p>Voici les comptes de l'année en cours</p>

    <table>
		<thead>
			<tr>
				<th>Opérations</th>
				<th>Recettes</th>
				<th>Dépenses</th>
				<th>Solde</th>
				<th>Commentaires</th>
			</tr>
		</thead>
		<tbody>
		<tr>
				<td>Solde 2022</td>
				<td>600</td>
				<td></td>
				<td>600</td>
				<td>Base cotisation 80 euros</td>
			</tr>
			<tr>
				<td>Séance du 23/09</td>
				<td></td>
				<td>240</td>
				<td>360</td>
				<td></td>
			</tr>
			<tr>
				<td>Cotisations 5/10</td>
				<td>1400</td>
				<td></td>
				<td>1760</td>
				<td></td>
			</tr>
			<tr>
				<td>Séance Charlotte 5/10</td>
				<td></td>
				<td>180</td>
				<td>1580</td>
				<td></td>
			</tr>
			<tr>
				<td>Photocopies</td>
				<td></td>
				<td>74</td>
				<td>1506</td>
				<td></td>
			</tr>
			<tr>
				<td>Séance Charlotte 19/11</td>
				<td></td>
				<td>180</td>
				<td>1326</td>
				<td></td>
			</tr>
			<tr>
				<td>Photocopies 19/11</td>
				<td>10</td>
				<td></td>
				<td>1316</td>
				<td></td>
			</tr>
			<tr>
				<td>Cotisations 19/11</td>
				<td>680</td>
				<td></td>
				<td>1996</td>
				<td></td>
			</tr>
			<tr>
				<td>Cotisations 10/12</td>
				<td>230</td>
				<td></td>
				<td>2226</td>
				<td></td>
			</tr>
			<tr>
				<td>Séance Charlotte 10/12</td>
				<td></td>
				<td>300</td>
				<td>1926</td>
				<td></td>
			</tr>
			<tr>
				<td>Cotisations 14/01</td>
				<td>80</td>
				<td></td>
				<td>2006</td>
				<td></td>
			</tr>
			<tr>
				<td>Séance Charlotte 14/01</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
		</tbody>
	</table>

</main>