<main id="membersSongDetail">

	<figure>
		<img class="logo" src="../assets/img/logo1.png" alt="Logo des Luttes Enchantées">
	</figure>

	<?php
		$title = $data["song"]["title"];
		$description = $data["song"]["description"];

		if(isset($data["song"]) && $data["song"] !== "")
		{
			$urlVideo = $data["song"]["url_video"];
		}
		else
		{
	      $urlVideo = "";
		}

		if(isset($data["voices"]) && $data["voices"] !== "")
		{
			$voices = $data["voices"];
		}
		else
		{
	      $voices = "";
		}

		if(isset($data["text"]) && $data["text"] !== [])
		{
			$urlText = $data["text"]["url"];
		}
		else
		{
	      	$urlText = "";
		}
	?>
	<h1><?= $title; ?></h1>

	<p class="songDetailDescr"><?= $description; ?>

	<?php
	if($voices !== "")
	{
	?>
		<ul>
			<?php
			foreach($voices as $key => $voice)
			{
			?>
				<li>
					<figure class="songDetailFig">
						<figcaption class="songDetailFigCap"><?= $voice["voice_type"]; ?></figcaption>
						<audio class="songDetailAudio"
							controls
							src="<?= $voice['url']; ?>">
								<a href="<?= $voice['url']; ?>">
								Download audio
								</a>
						</audio>
					</figure>

				</li>
			<?php
			}
			?>
		</ul>
	<?php
	}
	?>

	<?php
	if($urlText !== "")
	{
	?>
		<figure class="songDetailText">
			<iframe src="<?= $urlText; ?>"> </iframe> 
		</figure>
	<?php
	}
	?>


	<?php
	if($urlVideo !== "")
	{
	?>
		<figure class="songDetailVideo">
			<?= $urlVideo; ?>
		</figure>
	<?php
	}
	?>

</main>