<main id="membersEventDetail">

      <figure>
            <img class="logo" src="../assets/img/logo1.png" alt="Logo des Luttes Enchantées">
	</figure>

      <?php
	$event = $data["event"];
	$id = $event->getId();
      $date = $event->getDate();
      $tempDate = explode("-", $date);
      $dateForInput = $tempDate[2] . "-" . $tempDate[1] . "-" . $tempDate[0];
      $eventCatId = $event->getEventCatId();
      $privateDetails = $event->getPrivateDetails();
      $publicDetails = $event->getPublicDetails();
      $status = $event->getStatus();
      $cat = $data["cat"];
	?>

	<h1><?= $cat; ?> du <?= $date; ?></h1>

	<h2>Infos internes : </h2>

      <p><?= $privateDetails; ?></p>
      
      <h2>Infos publiques : </h2>
      
	<p><?= $publicDetails; ?></p>

      <h2>Participantes</h2>

      <h3>Présentes : <?= $data["count"]["oui"]; ?></h3>

      <ul>

      <?php
            foreach($data["parts"] as $key => $part)
            {
                  if($part["status"] === "Oui")
                  {
                  ?>
                        <li><?= $part["user_name"]; ?></li>
                  <?php
                  }
            }
      ?>

      </ul>

      <h3>Absentes : <?= $data["count"]["non"]; ?></h3>

      <ul>

      <?php
            foreach($data["parts"] as $key => $part)
            {
                  if($part["status"] === "Non")
                  {
                  ?>
                        <li><?= $part["user_name"]; ?></li>
                  <?php
                  }
            }
      ?>

      </ul>

      <h3>Ne savent pas : <?= $data["count"]["nsp"]; ?></h3>

      <ul>

      <?php
            foreach($data["parts"] as $key => $part)
            {
                  if($part["status"] === "Je ne sais pas")
                  {
                  ?>
                        <li><?= $part["user_name"]; ?></li>
                  <?php
                  }
            }
      ?>

      </ul>

      <h3>Non répondu : <?= $data["count"]["nonrep"]; ?></h3>

      <ul>

      <?php
            foreach($data["parts"] as $key => $part)
            {
                  if($part["status"] === "Non répondu")
                  {
                  ?>
                        <li><?= $part["user_name"]; ?></li>
                  <?php
                  }
            }
      ?>

      </ul>

</main>