<main id="membersEvents">

       <h1>Agenda</h1>

       <h2>Voici les évenements à venir :</h2>

       <?php
		foreach($data["events"] as $key => $event)
		{
		?>
			<article class=membersEventsItem>
				<h3 class="membEvDate"><?= $event["date"]; ?></h3>
				<?php
				foreach($data["cats"] as $key => $cat)
				{
					if($cat["id"] === $event["event_cat_id"])
					{
					?>
						<p class="membEvCatName"><?=$cat["name"]; ?></p>
					<?php
					}
				}

				if($event["status"] === "1")
				{
				?>
					<p class="membEvStat">Evenement privé</p>
				<?php
				}
				else
				{
				?>
					<p class="membEvStat">Evenement public</p>
				<?php	
				}
				?>
				<p class="membEvPres">Présentes : <?= $event["oui"]; ?></p>
				<p class="membEvAbs">Absentes : <?= $event["non"]; ?></p>
				<p class="membEvNSP">Ne savent pas : <?= $event["nsp"]; ?></p>
				<p class="membEvNRep">Non répondu : <?= $event["nonrep"]; ?></p>
				
				<p class="membEvPrivDet"><?= $event["private_details"]; ?></p>

				<?php
				$id = intval($event["id"]);
				?>

				<form class="displayUpdateEventForm"
					action="/Luttes-Enchantees/detail-date/<?= $id; ?>"
					method="post">

					<input type="hidden"
						id="route"
						name="route"
						value="param">
					<input type="hidden"
						id="eventDetail"
						name="action"
						value="eventDetail">
					<input type="hidden"
						id="eventId"
						name="eventId"
						value="<?= $id; ?>">
					<input class="button"
						type="submit"
						value="Voir le détail">
				</form>
			</article>
		<?php
		}
		?>
	</section>


</main>