<main id="membersSongs">

	<figure>
		<img class="logo" src="./assets/img/logo1.png" alt="Logo des Luttes Enchantées">
	</figure>
	
	<h1>Liste des chants</h1>

	<p>Pour voir le détail d'un chant (paroles, voix) cliquer dessus</p>

	<ul>
		<?php
		foreach($data["allSongs"] as $key => $song)
		{
		?>
		<li>
			<form class="songsForDetail"
				method="POST"
				action="/Luttes-enchantees/detail-chant/<?= $song["id"]; ?>">
				
				<input type="hidden" name="route" value="param">
				<input type="hidden"
					name="id"
					value="<?= $song["id"] ?>">
					
				<input class="button" type="submit" value="<?= $song["title"]; ?>">
				
            	</form>
		</li>
		<?php
		}
		?>
	</ul>

</main>