<main id="membersSongDetail">
	<?php
		$title = $data["song"]["title"];
		$description = $data["song"]["description"];

		if(isset($data["song"]) && $data["song"] !== "")
		{
			$urlVideo = $data["song"]["url_video"];
		}
		else
		{
	      $urlVideo = "";
		}

		if(isset($data["voices"]) && $data["voices"] !== "")
		{
			$voices = $data["voices"];
		}
		else
		{
	      $voices = "";
		}

		if(isset($data["text"]) && $data["text"] !== [])
		{
			$urlText = $data["text"]["url"];
		}
		else
		{
	      	$urlText = "";
		}
	?>
	<h1><?= $title; ?></h1>

	<p><?= $description; ?>

	<?php
	if($voices !== "")
	{
	?>
		<ul>
			<?php
			foreach($voices as $key => $voice)
			{
			?>
				<li>

					<figure>
						<figcaption><?= $voice["voice_type"]; ?></figcaption>
						<audio
							controls
							src="<?= $voice['url']; ?>">
								<a href="<?= $voice['url']; ?>">
								Download audio
								</a>
						</audio>
					</figure>

				</li>
			<?php
			}
			?>
		</ul>
	<?php
	}
	?>

	<?php
	if($urlVideo !== "")
	{
	?>
		<?= $urlVideo; ?>
	<?php
	}
	?>

	<?php
	if($urlText !== "")
	{
	?>
		<iframe src="<?= $urlText; ?>" width="100%" height="500px"> </iframe> 
	<?php
	}
	?>
</main>