<main id="membersSongDetail">

	<figure>
		<img class="logo" src="../assets/img/logo1.png" alt="Logo des Luttes Enchantées">
	</figure>

	<?php
		$title = $data["song"]["title"];
		$description = $data["song"]["description"];

		if(isset($data["song"]) && $data["song"] !== "")
		{
			$urlVideo = $data["song"]["url_video"];
		}
		else
		{
	      $urlVideo = "";
		}

		if(isset($data["voices"]) && $data["voices"] !== "")
		{
			$voices = $data["voices"];
		}
		else
		{
	      $voices = "";
		}

		if(isset($data["text"]) && $data["text"] !== [])
		{
			$urlText = $data["text"]["url"];
		}
		else
		{
	      	$urlText = "";
		}
	?>
	<h1><?= $title; ?></h1>

	<p class="songDetailDescr"><?= $description; ?>

	<?php
	if($voices !== "")
	{
	?>
		<ul>
			<?php
			foreach($voices as $key => $voice)
			{
			?>
				<li>
					<figure class="songDetailFig">
						<figcaption class="songDetailFigCap"><?= $voice["voice_type"]; ?></figcaption>
						<audio class="songDetailAudio"
							controls
							src="<?= $voice['url']; ?>">
								<a href="<?= $voice['url']; ?>">
								Download audio
								</a>
						</audio>
					</figure>

				</li>
			<?php
			}
			?>
		</ul>
	<?php
	}
	?>

	<?php
	if($urlText !== "")
	{
	?>
		<figure class="songDetailText">
			<iframe src="<?= $urlText; ?>"> </iframe> 
		</figure>
	<?php
	}
	?>


	<?php
	if($urlVideo !== "")
	{
	?>
		<figure class="songDetailVideo">
			<?= $urlVideo; ?>
		</figure>
	<?php
	}
	?>

	<section class="tutoEnregistrement">
		<h2>Pour info</h2>
		<p>Pour enregistrer un fichier son, fais un clic droit sur le lecteur audio et tu trouveras "Enregistrer le fichier audio sous...".</p>
		<figure class="tuto">
			<img class="tutoEnr1" src="../assets/img/tutoEnrSon.png" alt="Illustration tuto enregistrement son">
		</figure>
		<figure class="tuto">
			<img class="tutoEnr2" src="../assets/img/tutoEnrSon2.png" alt="Illustration tuto enregistrement son 2">
		</figure>
		<p>Tu n'auras plus qu'à choisir un dossier dans ton ordi pour l'enregistrer.</p>

		<p class="tutoEnrTxt">Pour Enregistrer un texte, il y a un petit dossier avec une flèche en haut à droite du texte.</p>
		<figure class="tuto">
			<img class="tutoEnr3" src="../assets/img/tutoEnrTxt.png" alt="Illustration tuto enregistrement texte">
		</figure>
		<p>En cliquant dessus, ça ouvre une fenêtre pour pouvoir choisir un dossier dans ton ordi pour l'enregistrer.</p>
	</section>

</main>